#!/usr/bin/env node
// build-edit.mjs: writes the footage slots of composition/index.html from composition/edit.json (between FOOTAGE:BEGIN and FOOTAGE:END)
// and copies the clips from video/footage/ into composition/footage/ (both gitignored). The footage itself is never retimed:
// every slot plays its clip at normal speed from data-media-start; the only treatment is a slow 1.00 -> 1.025 push-in.
// Usage: node video/tools/build-edit.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const video = path.resolve(here, '..');
const comp = path.join(video, 'composition');
const edit = JSON.parse(fs.readFileSync(path.join(comp, 'edit.json'), 'utf8'));
fs.mkdirSync(path.join(comp, 'footage'), { recursive: true });
for (const src of new Set(edit.segments.map((s) => s.src))) {
  const from = path.join(video, src);
  if (!fs.existsSync(from)) throw new Error(`missing clip ${from} (run tools/capture-gameplay.mjs, see video/README.md)`);
  fs.copyFileSync(from, path.join(comp, src));
}
const r = (n) => Math.round(n * 1000) / 1000;
const lines = [];
const tracks = [];
for (const s of edit.segments) {
  const cls = s.layout === 'left' ? 'vid half left' : s.layout === 'right' ? 'vid half right' : 'vid';
  lines.push(`      <video id="v-${s.id}" class="${cls}" src="${s.src}" data-start="${r(s.start)}" data-duration="${r(s.dur)}" data-media-start="${r(s.mediaStart)}" data-track-index="${s.layout === 'right' ? 3 : 2}" muted playsinline></video>`);
  tracks.push(`[${JSON.stringify('#v-' + s.id)}, ${r(s.start)}, ${r(s.dur)}]`);
}
const block = `<!-- FOOTAGE:BEGIN (generated by video/tools/build-edit.mjs from edit.json) -->
${lines.join('\n')}
      <!-- FOOTAGE:END -->`;
const pushIn = `/* PUSHIN:BEGIN */ var PUSH = [${tracks.join(', ')}]; /* PUSHIN:END */`;
const idx = path.join(comp, 'index.html');
let html = fs.readFileSync(idx, 'utf8');
html = html.replace(/<!-- FOOTAGE:BEGIN[\s\S]*?<!-- FOOTAGE:END -->/, block).replace(/\/\* PUSHIN:BEGIN \*\/[\s\S]*?\/\* PUSHIN:END \*\//, pushIn);
fs.writeFileSync(idx, html);
console.log(`edit: ${edit.segments.length} footage slots, total ${edit.total} s`);
